key: some secret key
slack:
  token: xoxb-bot-token
  signingSecret: signing secret from slack
  channel: "#channel-to-post-to"
  verification: shared secret with slack
unity:
  baseUrl: https://build-api.cloud.unity3d.com/api/v1
  apiKey: api key from unity
  secret: shared secret with unity
ssh:
  host: your.deploymachine.com
  user: builduser
  pass: sshpassword
  keyfile: ssh.key